config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#hello'

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    render :new and return if @post.content.nil?
    @post.save
    redirect_to @post
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def hello
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quick Posts</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Gloria+Hallelujah" rel="stylesheet">

  </head>
  <body style='background-color: #f1f1f1'>
    <div class="container">
      <header class="text-center">
        <h1 style="margin-bottom: -20px; font-family: 'Gloria Hallelujah', cursive;">Quick Posts</h1>
        <h3 style="font-family: 'Amatic SC', cursive;">Write quick anonymous notes to share</h3>
      </header>

      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/new.html.erb
<h1>Write something</h1>
<br>
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= md_simple_editor  do %>
      <%= f.text_area :content, class: 'form-control', rows: 10 %>
    <% end %>
  </div>
  <br>
  <div class="text-center">
    <%= f.submit class: 'btn btn-lg btn-info' %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="show-post">
  <% markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true) %>
  <%= markdown.render(@post.content).html_safe %>
</div>

<br>

<div class="text-center">
  <a class='copy-text'>Click here to copy post URL</a>
  <input type="text" class="url-to-copy" value="<%= post_url(@post) %>">
  <div class="alert alert-info" role="alert" style="display: none">
    URL Copied
  </div>


  <div style="margin-top: 20px">
    <%= link_to 'Create A Post', new_post_path, class: 'btn btn-lg btn-info' %>
  </div>
</div>

<script>
  $(function () {
    $('.copy-text').click(function(e) {
      e.preventDefault();
      $('.url-to-copy').select();
      document.execCommand("copy");
      $('.alert-info').show().fadeOut(3000);
    })
  })
</script>

app/views/welcome/hello.html.erb
Hello